# Build stage
FROM node:23.4.0-bookworm-slim

WORKDIR /app

COPY package.json ./

RUN npm install -g npm && npm install --force

RUN npm install @swc/core-linux-arm64-gnu @next/swc-linux-arm64-musl \
    @next/swc-wasm-nodejs @next/swc-wasm-web


COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]