services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: ./Dockerfile.dev
  #   image: shamiri/journal-frontend:latest
  #   container_name: journal-frontend
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend

  backend:
    build: ./backend
    image: shamiri/journal-backend:latest
    container_name: journal-backend
    restart: unless-stopped
    env_file:
      - ./config/backend.env
    ports:
      - 8000:8000
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: bitnami/mysql:8.4.3
    container_name: journal-db
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
    volumes:
      - ./db/data:/bitnami/mysql/data
      - ./db/setup/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql

  # TODO: Setup ai provider
  # ai:
  #   restart: unless-stopped
  #   networks:
  #     - app-network

networks:
  app-network:
